apiVersion: apps/v1
kind: Deployment
metadata:
  name: addressbook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: addressbook
  template:
    metadata:
      labels:
        app: addressbook
        deployment: addressbook
    spec:
      containers:
      - name: containerdocker-cicd-kubernetes
        image: registry.digitalocean.com/$REGISTRY_NAME/cicd_docker_kubernetes:$SEMAPHORE_WORKFLOW_ID
        readinessProbe:
            httpGet:
              path: /ready
              port: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "$PORT"
        - name: DB_SCHEMA
          value: "$DB_SCHEMA"
        - name: DB_USER
          value: "$DB_USER"
        - name: DB_PASSWORD
          value: "$DB_PASSWORD"
        - name: DB_HOST
          value: "$DB_HOST"
        - name: DB_PORT
          value: "$DB_PORT"
        - name: DB_SSL
          value: "$DB_SSL"
